language: perl
perl:
  #- "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18.1-thr"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "blead"

env:
  - WITHOUT_RECOMMENDS=0
  - WITHOUT_RECOMMENDS=1

matrix:
  allow_failures:
    - perl: blead
  exclude:
    - perl: "5.10"
      env: WITHOUT_RECOMMENDS=1
    - perl: "5.12"
      env: WITHOUT_RECOMMENDS=1
    - perl: "5.14"
      env: WITHOUT_RECOMMENDS=1

sudo: false

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
  - cpan-install ExtUtils::MakeMaker~6.68
  - if [ "$WITHOUT_RECOMMENDS" = "1" ]; then
        for f in "META.json" "META.yml" "Makefile.PL"; do
            cat $f | grep -P -v 'Filter::signatures|MIME::Detect|Text::CleanFragment|^recommends:' > $$ && mv -f $$ $f;
        done;
    fi
  - cpan-install --deps

script:
  - cd $BUILD_DIR
  - cpanm --installdeps .
  - perl Makefile.PL && make
  - prove --version
  - prove -blv $(test-dirs)

branches:
  except:
    - /^wip\//
    - /^blocked/
#notifications:
#  email: false
#  irc:
#    channels:
#      - "irc.perl.org#moo-smoke"
#    template:
#      - "%{repository}#%{build_number} %{branch} by %{author}: %{message} (%{build_url})"
#    on_success: change
#    on_failure: always
#    skip_join: true
