---
abstract: 'handle resumable multi-part HTTP uploads with flowjs'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Upload-FlowJs
no_index:
  directory:
    - t
    - inc
provides:
  HTTP::Upload::FlowJs:
    file: lib/HTTP/Upload/FlowJs.pm
    version: '0.01'
requires:
  Carp: '0'
  Data::Dumper: '0'
  JSON: '0'
  Test::More: '0'
  perl: '5.010'
recommends:
  Filter::signatures: '0.10'
  MIME::Detect: '0'
  Text::CleanFragment: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Corion/HTTP-Upload-FlowJs.git
version: '0.01'
x_static_install: 1
